const http = require('http');
const fs = require('fs');
const path = require('path');

try {
  process.loadEnvFile(path.join(__dirname, '.env'));
} catch {
  // Without .env the key can still come from the real environment.
}

const PORT = Number(process.env.PORT) || 3000;
const TMDB_API_KEY = (process.env.TMDB_API_KEY || '').trim();
const TMDB_API_BASE = process.env.TMDB_API_BASE || 'https://api.themoviedb.org/3';
const LANGUAGE = 'pt-BR';
const REGION = 'BR';
const MAX_PAGE = 500;
const CACHE_TTL_MS = Number(process.env.CACHE_TTL_MS) || 10 * 60 * 1000;
const CACHE_MAX_ENTRIES = 500;
const PUBLIC_DIR = path.join(__dirname, 'public');
const SAGAS_FILE = path.join(__dirname, 'data', 'sagas.json');
const SAGA_SEARCH_LIMIT = 20;

// Hand-built sagas (movies + series) generated by `npm run sagas`.
const sagaData = loadSagaData();
const curatedMembership = new Map();
for (const saga of sagaData.curated) {
  for (const item of saga.items) {
    const key = `${item.type}:${item.id}`;
    const entries = curatedMembership.get(key) || [];
    entries.push({ kind: 'curated', id: saga.slug, name: saga.name, position: item.storyOrder, total: saga.items.length });
    curatedMembership.set(key, entries);
  }
}

function loadSagaData() {
  try {
    const parsed = JSON.parse(fs.readFileSync(SAGAS_FILE, 'utf8'));
    return { curated: parsed.curated || [], featured: parsed.featured || [] };
  } catch {
    console.warn('Aviso: data/sagas.json não encontrado. Rode "npm run sagas" para gerar as sagas.');
    return { curated: [], featured: [] };
  }
}

const MIME_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon'
};

const SECURITY_HEADERS = {
  'Content-Security-Policy':
    "default-src 'self'; img-src 'self' https://image.tmdb.org https://archive.org https://*.archive.org data:; media-src https://archive.org https://*.archive.org; frame-src https://www.youtube-nocookie.com https://archive.org; object-src 'none'; base-uri 'none'; form-action 'self'",
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin'
};

const CATEGORY_TYPES = { movies: 'movie', series: 'tv' };
const RELEASE_DATE_FIELDS = { movie: 'primary_release_date', tv: 'first_air_date' };
const CREDITS_KEYS = { movie: 'credits', tv: 'aggregate_credits' };
const MIN_VOTES_FOR_RATING_FILTER = 100;
const CAST_LIMIT = 15;
const RECOMMENDATIONS_LIMIT = 12;
const TOP_LIMIT = 10;
const REMINDER_CHECK_LIMIT = 40;
const ARCHIVE_BASE = 'https://archive.org';
const PUBLIC_DOMAIN_PAGE_SIZE = 24;
// Genre "exploitation" films (B horror, crime, action) are allowed; sexual content and nudity are not.
const BLOCKED_SUBJECTS = ['sex', 'sexploitation', 'nudity', 'nudist', 'erotic', 'adult', 'striptease'];
const BLOCKED_TITLE_WORDS = ['sex', 'nude', 'nudist', 'naked', 'erotic', 'striptease'];
// Ethnographic "exploitation" documentaries and Maniac (1934) are tagged loosely but contain nudity.
const BLOCKED_SUBJECT_PHRASES = ['ethno-exploitation'];
const BLOCKED_TITLE_YEARS = [{ title: 'maniac', year: '1934' }];

// Only items that declare a public-domain license, have an MP4 the browser can play, and pass the content rules.
const PUBLIC_DOMAIN_QUERY = [
  'collection:(feature_films)',
  'mediatype:(movies)',
  'licenseurl:(*publicdomain*)',
  'format:("h.264" OR "512Kb MPEG4")',
  `-subject:(${BLOCKED_SUBJECTS.join(' OR ')})`,
  `-title:(${BLOCKED_TITLE_WORDS.join(' OR ')})`,
  ...BLOCKED_SUBJECT_PHRASES.map((phrase) => `-subject:("${phrase}")`),
  ...BLOCKED_TITLE_YEARS.map((entry) => `NOT (title:(${entry.title}) AND year:(${entry.year}))`)
].join(' AND ');

// The same rules applied to a single item, so a direct link cannot open something the list hides.
function isBlockedContent(meta) {
  const words = (value) => [].concat(value || []).join(' ').toLowerCase();
  const subjects = words(meta.subject);
  const title = words(meta.title);
  const year = String([].concat(meta.year || meta.date || [])[0] || '').slice(0, 4);
  const hasWord = (text, word) => new RegExp(`(^|[^a-z])${word}([^a-z]|$)`).test(text);

  return BLOCKED_SUBJECTS.some((word) => hasWord(subjects, word)) ||
    BLOCKED_TITLE_WORDS.some((word) => hasWord(title, word)) ||
    BLOCKED_SUBJECT_PHRASES.some((phrase) => subjects.includes(phrase)) ||
    BLOCKED_TITLE_YEARS.some((entry) => hasWord(title, entry.title) && year === entry.year);
}
const IN_THEATERS_DAYS = 90;
const ABROAD_PROVIDERS_LIMIT = 6;
// Countries listed first when a title is only available abroad.
const PREFERRED_COUNTRIES = ['PT', 'US', 'GB', 'ES', 'CA', 'MX', 'AR', 'FR', 'IT', 'DE', 'JP'];

// Main subscription services in Brazil, matched by name because TMDB ids are not documented as stable.
const FEATURED_PLATFORMS = [
  { label: 'Netflix', match: /^netflix$/i },
  { label: 'Prime Video', match: /^amazon prime video$/i },
  { label: 'Disney+', match: /^disney plus$/i },
  { label: 'HBO Max', match: /^(hbo )?max$/i },
  { label: 'Globoplay', match: /^globoplay$/i },
  { label: 'Apple TV+', match: /^apple tv\+?$/i },
  { label: 'Paramount+', match: /^paramount (plus|\+)$/i },
  { label: 'Crunchyroll', match: /^crunchyroll$/i }
];

class HttpError extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
}

const cache = new Map();

async function tmdbGet(endpoint, params = {}) {
  if (!TMDB_API_KEY) {
    throw new HttpError(500, 'Chave do TMDB não configurada. Crie o arquivo .env com TMDB_API_KEY=sua_chave.');
  }

  const url = new URL(TMDB_API_BASE + endpoint);
  for (const [key, value] of Object.entries({ language: LANGUAGE, ...params })) {
    url.searchParams.set(key, value);
  }

  const cacheKey = url.toString();
  const cached = cache.get(cacheKey);
  if (cached && cached.expiresAt > Date.now()) return cached.data;

  const headers = { accept: 'application/json' };
  // TMDB accepts either a v4 read access token (a JWT, starts with "eyJ") or a v3 api_key.
  if (TMDB_API_KEY.startsWith('eyJ')) {
    headers.authorization = `Bearer ${TMDB_API_KEY}`;
  } else {
    url.searchParams.set('api_key', TMDB_API_KEY);
  }

  let response;
  try {
    response = await fetch(url, { headers, signal: AbortSignal.timeout(10000) });
  } catch {
    throw new HttpError(502, 'Não foi possível conectar ao TMDB. Verifique sua internet.');
  }

  if (response.status === 401) throw new HttpError(500, 'Chave do TMDB inválida. Confira o TMDB_API_KEY no arquivo .env.');
  if (response.status === 404) throw new HttpError(404, 'Título não encontrado.');
  if (response.status === 429) throw new HttpError(503, 'Muitas requisições ao TMDB. Tente novamente em alguns segundos.');
  if (!response.ok) throw new HttpError(502, `O TMDB respondeu com erro ${response.status}.`);

  const data = await response.json();
  if (cache.size >= CACHE_MAX_ENTRIES) cache.delete(cache.keys().next().value);
  cache.set(cacheKey, { data, expiresAt: Date.now() + CACHE_TTL_MS });
  return data;
}

function parsePage(value) {
  const page = Number.parseInt(value, 10);
  return Number.isInteger(page) && page >= 1 ? Math.min(page, MAX_PAGE) : 1;
}

function toSummary(item, type) {
  return {
    id: item.id,
    type,
    title: item.title || item.name || 'Sem título',
    year: (item.release_date || item.first_air_date || '').slice(0, 4),
    releaseDate: item.release_date || item.first_air_date || null,
    poster: item.poster_path || null,
    rating: typeof item.vote_average === 'number' ? item.vote_average : null
  };
}

function toPageResult(data, items) {
  return {
    page: data.page,
    totalPages: Math.min(data.total_pages || 1, MAX_PAGE),
    results: items
  };
}

function parseYear(value) {
  const year = Number.parseInt(value, 10);
  return Number.isInteger(year) && year >= 1870 && year <= 2100 ? year : null;
}

async function handleList(searchParams) {
  const page = parsePage(searchParams.get('page'));
  const type = CATEGORY_TYPES[searchParams.get('category')];

  if (!type) {
    const data = await tmdbGet('/trending/all/week', { page });
    const items = data.results
      .filter((item) => item.media_type === 'movie' || item.media_type === 'tv')
      .map((item) => toSummary(item, item.media_type));
    return toPageResult(data, items);
  }

  const params = { page, sort_by: 'popularity.desc', include_adult: 'false' };
  const dateField = RELEASE_DATE_FIELDS[type];

  const genre = searchParams.get('genre') || '';
  if (/^\d{1,7}$/.test(genre)) params.with_genres = genre;

  const from = parseYear(searchParams.get('from'));
  const to = parseYear(searchParams.get('to'));
  if (from) params[`${dateField}.gte`] = `${from}-01-01`;
  if (to) params[`${dateField}.lte`] = `${to}-12-31`;

  const rating = Number(searchParams.get('rating'));
  if (Number.isFinite(rating) && rating > 0 && rating < 10) {
    params['vote_average.gte'] = String(rating);
    // Without a vote floor, titles with a single 10/10 vote dominate the results.
    params['vote_count.gte'] = String(MIN_VOTES_FOR_RATING_FILTER);
  }

  if (type === 'tv') params.include_null_first_air_dates = 'false';

  const data = await tmdbGet(`/discover/${type}`, params);
  return toPageResult(data, data.results.map((item) => toSummary(item, type)));
}

async function handlePlatforms() {
  const [movies, tv] = await Promise.all([
    tmdbGet('/watch/providers/movie', { watch_region: REGION }),
    tmdbGet('/watch/providers/tv', { watch_region: REGION })
  ]);
  const all = [...(movies.results || []), ...(tv.results || [])];

  const platforms = FEATURED_PLATFORMS.map((platform) => {
    const found = all.find((provider) => platform.match.test(provider.provider_name));
    return found ? { id: found.provider_id, name: platform.label, logo: found.logo_path || null } : null;
  }).filter(Boolean);

  return { platforms };
}

async function handlePlatformTop(searchParams) {
  const providerId = searchParams.get('provider') || '';
  if (!/^\d{1,7}$/.test(providerId)) throw new HttpError(400, 'Plataforma inválida.');

  const params = {
    watch_region: REGION,
    with_watch_providers: providerId,
    with_watch_monetization_types: 'flatrate',
    sort_by: 'popularity.desc',
    include_adult: 'false',
    page: '1'
  };
  const [movies, tv] = await Promise.all([
    tmdbGet('/discover/movie', params),
    tmdbGet('/discover/tv', params)
  ]);

  return {
    movies: movies.results.slice(0, TOP_LIMIT).map((item) => toSummary(item, 'movie')),
    series: tv.results.slice(0, TOP_LIMIT).map((item) => toSummary(item, 'tv'))
  };
}

async function handleCinema(searchParams) {
  const section = searchParams.get('section');
  const page = parsePage(searchParams.get('page'));

  if (section === 'now_playing') {
    const data = await tmdbGet('/movie/now_playing', { region: REGION, page });
    return toPageResult(data, data.results.map((item) => toSummary(item, 'movie')));
  }

  if (section !== 'upcoming') throw new HttpError(400, 'Seção de cinema inválida.');

  // With region set, TMDB filters release_date by the Brazilian release, not the worldwide one.
  const today = isoDate();
  const data = await tmdbGet('/discover/movie', {
    region: REGION,
    with_release_type: '2|3',
    'release_date.gte': today,
    sort_by: 'popularity.desc',
    include_adult: 'false',
    page
  });

  // List items only carry the worldwide date; the Brazilian one comes from each movie's release dates.
  const items = await Promise.all(data.results.map(async (item) => {
    const summary = toSummary(item, 'movie');
    try {
      const brazilDate = brazilTheatricalDate(await tmdbGet(`/movie/${item.id}/release_dates`));
      if (brazilDate) summary.releaseDate = brazilDate;
    } catch {
      // Keep the worldwide date if the lookup fails.
    }
    return summary;
  }));

  return toPageResult(data, items.filter((item) => item.releaseDate && item.releaseDate >= today));
}

function providerNames(list) {
  return [...new Set((list || []).map((provider) => provider.provider_name))];
}

async function handleReminderCheck(searchParams) {
  const keys = (searchParams.get('items') || '')
    .split(',')
    .map((key) => key.match(/^(movie|tv):(\d{1,10})$/))
    .filter(Boolean)
    .slice(0, REMINDER_CHECK_LIMIT);
  const today = isoDate();

  const results = await Promise.all(keys.map(async ([key, type, id]) => {
    try {
      const data = await tmdbGet(`/${type}/${id}`, {
        append_to_response: type === 'movie' ? 'watch/providers,release_dates' : 'watch/providers'
      });
      const brazil = (data['watch/providers'] && data['watch/providers'].results && data['watch/providers'].results[REGION]) || {};
      const theatrical = type === 'movie' ? brazilTheatricalDate(data.release_dates) : null;
      const releaseDate = theatrical || data.release_date || data.first_air_date || null;
      return {
        key,
        releaseDate,
        theatrical: Boolean(theatrical),
        released: Boolean(releaseDate && releaseDate <= today),
        streaming: providerNames([...(brazil.flatrate || []), ...(brazil.free || []), ...(brazil.ads || [])]),
        store: providerNames([...(brazil.rent || []), ...(brazil.buy || [])])
      };
    } catch {
      return { key, error: true };
    }
  }));

  return { results };
}

async function archiveGet(url) {
  const cached = cache.get(url);
  if (cached && cached.expiresAt > Date.now()) return cached.data;

  let response;
  try {
    response = await fetch(url, { headers: { accept: 'application/json' }, signal: AbortSignal.timeout(15000) });
  } catch {
    throw new HttpError(502, 'Não foi possível conectar ao Internet Archive. Tente novamente.');
  }
  if (!response.ok) throw new HttpError(502, `O Internet Archive respondeu com erro ${response.status}.`);

  const data = await response.json();
  if (cache.size >= CACHE_MAX_ENTRIES) cache.delete(cache.keys().next().value);
  cache.set(url, { data, expiresAt: Date.now() + CACHE_TTL_MS });
  return data;
}

function firstValue(value) {
  return Array.isArray(value) ? value[0] : value;
}

// Archive descriptions are free-form HTML; the page shows them as plain text.
function plainText(html) {
  return String(firstValue(html) || '')
    .replace(/<br\s*\/?>|<\/p>/gi, '\n')
    .replace(/<[^>]*>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/[ \t]+/g, ' ')
    .replace(/\n\s*\n+/g, '\n\n')
    .trim();
}

function toPublicSummary(doc) {
  return {
    id: doc.identifier,
    type: 'public',
    title: firstValue(doc.title) || doc.identifier,
    year: doc.year ? String(firstValue(doc.year)).slice(0, 4) : ''
  };
}

async function handlePublicDomainList(searchParams) {
  const page = parsePage(searchParams.get('page'));
  // Keep only letters, digits and spaces so user input cannot alter the search syntax.
  const text = (searchParams.get('q') || '').replace(/[^\p{L}\p{N}\s]/gu, ' ').trim().slice(0, 80);
  const query = text ? `${PUBLIC_DOMAIN_QUERY} AND (title:(${text}) OR subject:(${text}))` : PUBLIC_DOMAIN_QUERY;

  const url = new URL(`${ARCHIVE_BASE}/advancedsearch.php`);
  url.searchParams.set('q', query);
  for (const field of ['identifier', 'title', 'year']) url.searchParams.append('fl[]', field);
  url.searchParams.set('sort[]', 'downloads desc');
  url.searchParams.set('rows', String(PUBLIC_DOMAIN_PAGE_SIZE));
  url.searchParams.set('page', String(page));
  url.searchParams.set('output', 'json');

  const data = await archiveGet(url.toString());
  const total = (data.response && data.response.numFound) || 0;
  return {
    page,
    totalPages: Math.min(Math.ceil(total / PUBLIC_DOMAIN_PAGE_SIZE) || 1, MAX_PAGE),
    total,
    results: ((data.response && data.response.docs) || []).map(toPublicSummary)
  };
}

// One MP4 per part of the film: the h.264 derivative when it exists, otherwise the 512Kb one.
function playableSources(identifier, files) {
  const parts = new Map();
  for (const file of files || []) {
    if (!/\.mp4$/i.test(file.name || '')) continue;
    const part = file.name.replace(/(_512kb)?\.mp4$/i, '');
    const rank = file.format === 'h.264' ? 2 : 1;
    const current = parts.get(part);
    if (!current || rank > current.rank) parts.set(part, { name: file.name, rank });
  }

  const names = [...parts.values()].map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  return names.map((name, index) => ({
    label: names.length > 1 ? `Parte ${index + 1}` : 'Filme',
    url: `${ARCHIVE_BASE}/download/${encodeURIComponent(identifier)}/${name.split('/').map(encodeURIComponent).join('/')}`
  }));
}

async function handlePublicDomainItem(identifier) {
  const data = await archiveGet(`${ARCHIVE_BASE}/metadata/${encodeURIComponent(identifier)}`);
  const meta = data.metadata;
  if (!meta) throw new HttpError(404, 'Filme não encontrado no Internet Archive.');

  const license = String(firstValue(meta.licenseurl) || '');
  if (!/publicdomain/i.test(license)) throw new HttpError(404, 'Este filme não está marcado como domínio público.');
  if (isBlockedContent(meta)) throw new HttpError(404, 'Este filme não está disponível no CineGuia.');

  return {
    id: identifier,
    title: firstValue(meta.title) || identifier,
    year: meta.year ? String(firstValue(meta.year)).slice(0, 4) : (String(firstValue(meta.date) || '').match(/\d{4}/) || [''])[0],
    runtime: firstValue(meta.runtime) || null,
    director: firstValue(meta.director) || firstValue(meta.creator) || null,
    description: plainText(meta.description),
    license,
    sources: playableSources(identifier, data.files)
  };
}

function byReleaseDate(a, b) {
  // Undated (announced) titles go last.
  if (!a.releaseDate) return b.releaseDate ? 1 : 0;
  if (!b.releaseDate) return -1;
  return a.releaseDate.localeCompare(b.releaseDate);
}

function handleSagaList() {
  return {
    curated: sagaData.curated.map((saga) => {
      const items = [...saga.items].sort(byReleaseDate);
      const years = items.map((item) => (item.releaseDate || '').slice(0, 4)).filter(Boolean);
      return {
        id: saga.slug,
        name: saga.name,
        poster: (items.find((item) => item.poster) || {}).poster || null,
        movies: saga.items.filter((item) => item.type === 'movie').length,
        series: saga.items.filter((item) => item.type === 'tv').length,
        years: years.length ? `${years[0]}–${years[years.length - 1]}` : ''
      };
    }),
    featured: sagaData.featured
  };
}

async function handleSagaSearch(searchParams) {
  const query = (searchParams.get('q') || '').trim().slice(0, 100);
  if (!query) throw new HttpError(400, 'Digite o nome de uma saga.');
  const data = await tmdbGet('/search/collection', { query });
  return {
    results: (data.results || []).slice(0, SAGA_SEARCH_LIMIT).map((collection) => ({
      id: collection.id,
      name: collection.name,
      poster: collection.poster_path || null,
      backdrop: collection.backdrop_path || null
    }))
  };
}

async function handleCollectionSaga(id) {
  const data = await tmdbGet(`/collection/${id}`);
  const items = (data.parts || [])
    .map((part) => ({
      type: 'movie',
      id: part.id,
      title: part.title || part.original_title,
      releaseDate: part.release_date || null,
      poster: part.poster_path || null,
      overview: part.overview || ''
    }))
    .sort(byReleaseDate);

  return {
    kind: 'collection',
    id: data.id,
    name: data.name,
    description: data.overview || '',
    poster: data.poster_path || null,
    backdrop: data.backdrop_path || null,
    hasStoryOrder: false,
    items
  };
}

function handleCuratedSaga(slug) {
  const saga = sagaData.curated.find((item) => item.slug === slug);
  if (!saga) throw new HttpError(404, 'Saga não encontrada.');
  return {
    kind: 'curated',
    id: saga.slug,
    name: saga.name,
    description: saga.description,
    poster: null,
    backdrop: null,
    hasStoryOrder: true,
    items: [...saga.items].sort(byReleaseDate)
  };
}

function sagasForTitle(type, id, collection) {
  const sagas = [...(curatedMembership.get(`${type}:${id}`) || [])];
  if (collection && collection.id) sagas.push({ kind: 'collection', id: collection.id, name: collection.name });
  return sagas;
}

async function handleGenres(type) {
  const data = await tmdbGet(`/genre/${type}/list`);
  return { genres: (data.genres || []).map((genre) => ({ id: genre.id, name: genre.name })) };
}

async function handleSearch(searchParams) {
  const query = (searchParams.get('q') || '').trim().slice(0, 100);
  if (!query) throw new HttpError(400, 'Digite algo para buscar.');

  const data = await tmdbGet('/search/multi', {
    query,
    include_adult: 'false',
    page: parsePage(searchParams.get('page'))
  });
  const items = data.results
    .filter((item) => item.media_type === 'movie' || item.media_type === 'tv')
    .map((item) => toSummary(item, item.media_type));
  return toPageResult(data, items);
}

function pickTrailer(videos) {
  const youtube = (videos && videos.results ? videos.results : []).filter((video) => video.site === 'YouTube');
  const byPreference = (list) =>
    list.find((video) => video.iso_639_1 === 'pt' && video.official) ||
    list.find((video) => video.iso_639_1 === 'pt') ||
    list.find((video) => video.official) ||
    list[0];

  const trailer =
    byPreference(youtube.filter((video) => video.type === 'Trailer')) ||
    byPreference(youtube.filter((video) => video.type === 'Teaser'));
  return trailer ? { key: trailer.key, name: trailer.name } : null;
}

// TMDB has no per-title deep links, so known platforms open their own search for the title.
const PROVIDER_SEARCH_URLS = [
  { match: /netflix/i, url: (q) => `https://www.netflix.com/search?q=${q}` },
  { match: /prime video|amazon video/i, url: (q) => `https://www.primevideo.com/search?phrase=${q}` },
  { match: /^apple tv/i, url: (q) => `https://tv.apple.com/br/search?term=${q}` },
  { match: /google play/i, url: (q) => `https://play.google.com/store/search?q=${q}&c=movies` },
  { match: /youtube/i, url: (q) => `https://www.youtube.com/results?search_query=${q}` },
  { match: /crunchyroll/i, url: (q) => `https://www.crunchyroll.com/pt-br/search?q=${q}` }
];

function providerUrl(name, title, fallbackLink) {
  const known = PROVIDER_SEARCH_URLS.find((entry) => entry.match.test(name));
  return known ? known.url(encodeURIComponent(title)) : fallbackLink;
}

function mapProviders(list, title, fallbackLink) {
  const seen = new Set();
  return (list || [])
    .sort((a, b) => a.display_priority - b.display_priority)
    .filter((provider) => !seen.has(provider.provider_id) && seen.add(provider.provider_id))
    .map((provider) => ({
      name: provider.provider_name,
      logo: provider.logo_path || null,
      url: providerUrl(provider.provider_name, title, fallbackLink)
    }));
}

function mapCast(credits, type) {
  return ((credits && credits.cast) || []).slice(0, CAST_LIMIT).map((person) => ({
    name: person.name,
    character: type === 'tv' ? (person.roles && person.roles[0] && person.roles[0].character) || '' : person.character || '',
    photo: person.profile_path || null
  }));
}

function mapSeasons(seasons) {
  // Season 0 holds specials; it goes last so the default pick is season 1.
  return (seasons || [])
    .map((season) => ({
      number: season.season_number,
      name: season.name,
      episodeCount: season.episode_count || 0,
      year: (season.air_date || '').slice(0, 4)
    }))
    .sort((a, b) => (a.number === 0) - (b.number === 0) || a.number - b.number);
}

async function handleSeason(id, seasonNumber) {
  const data = await tmdbGet(`/tv/${id}/season/${seasonNumber}`);
  return {
    number: data.season_number,
    name: data.name,
    episodes: (data.episodes || []).map((episode) => ({
      number: episode.episode_number,
      name: episode.name,
      overview: episode.overview || '',
      airDate: episode.air_date || null,
      runtime: episode.runtime || null,
      still: episode.still_path || null
    }))
  };
}

function isoDate(daysFromToday = 0) {
  const date = new Date();
  date.setUTCDate(date.getUTCDate() + daysFromToday);
  return date.toISOString().slice(0, 10);
}

function brazilTheatricalDate(releaseDates) {
  const brazil = ((releaseDates && releaseDates.results) || []).find((entry) => entry.iso_3166_1 === REGION);
  // TMDB release types 2 and 3 are limited and wide theatrical releases.
  const dates = ((brazil && brazil.release_dates) || [])
    .filter((release) => release.type === 2 || release.type === 3)
    .map((release) => (release.release_date || '').slice(0, 10))
    .filter(Boolean)
    .sort();
  return dates[0] || null;
}

function releaseStatus(type, data) {
  const today = isoDate();

  if (type === 'movie') {
    const theatrical = brazilTheatricalDate(data.release_dates);
    if (theatrical && theatrical > today) return { kind: 'upcoming_theaters', date: theatrical };
    if (theatrical && theatrical >= isoDate(-IN_THEATERS_DAYS)) return { kind: 'in_theaters', date: theatrical };
    if (!theatrical && data.release_date && data.release_date > today) return { kind: 'upcoming', date: data.release_date };
    return null;
  }

  if (data.first_air_date && data.first_air_date > today) return { kind: 'upcoming', date: data.first_air_date };
  if (!data.first_air_date && ['In Production', 'Planned', 'Post Production'].includes(data.status)) {
    return { kind: 'in_production' };
  }
  return null;
}

function mapAbroad(resultsByCountry) {
  const byProvider = new Map();
  for (const [country, info] of Object.entries(resultsByCountry || {})) {
    if (country === REGION) continue;
    for (const provider of [...(info.flatrate || []), ...(info.free || []), ...(info.ads || [])]) {
      const entry = byProvider.get(provider.provider_name) ||
        { name: provider.provider_name, logo: provider.logo_path || null, countries: new Set() };
      entry.countries.add(country);
      byProvider.set(provider.provider_name, entry);
    }
  }

  const rank = (country) => {
    const index = PREFERRED_COUNTRIES.indexOf(country);
    return index === -1 ? PREFERRED_COUNTRIES.length : index;
  };

  return [...byProvider.values()]
    .map((entry) => ({
      name: entry.name,
      logo: entry.logo,
      countries: [...entry.countries].sort((a, b) => rank(a) - rank(b) || a.localeCompare(b))
    }))
    .sort((a, b) => b.countries.length - a.countries.length)
    .slice(0, ABROAD_PROVIDERS_LIMIT);
}

async function handleTitle(type, id) {
  const creditsKey = CREDITS_KEYS[type];
  const extras = type === 'movie' ? ',release_dates' : '';
  const data = await tmdbGet(`/${type}/${id}`, {
    append_to_response: `videos,watch/providers,${creditsKey},recommendations${extras}`,
    include_video_language: 'pt,en,null'
  });

  let overview = data.overview;
  if (!overview) {
    const english = await tmdbGet(`/${type}/${id}`, { language: 'en-US' });
    overview = english.overview;
  }

  const providersByCountry = (data['watch/providers'] && data['watch/providers'].results) || {};
  const brazil = providersByCountry[REGION] || {};
  const title = data.title || data.name;
  const watchLink = brazil.link || null;
  const providers = {
    link: watchLink,
    streaming: mapProviders(brazil.flatrate, title, watchLink),
    free: mapProviders([...(brazil.free || []), ...(brazil.ads || [])], title, watchLink),
    rent: mapProviders(brazil.rent, title, watchLink),
    buy: mapProviders(brazil.buy, title, watchLink)
  };
  const availableInBrazil = ['streaming', 'free', 'rent', 'buy'].some((key) => providers[key].length);

  return {
    id: data.id,
    type,
    title,
    originalTitle: data.original_title || data.original_name,
    year: (data.release_date || data.first_air_date || '').slice(0, 4),
    overview: overview || '',
    genres: (data.genres || []).map((genre) => genre.name),
    runtime: type === 'movie' ? data.runtime || null : null,
    rating: typeof data.vote_average === 'number' ? data.vote_average : null,
    poster: data.poster_path || null,
    backdrop: data.backdrop_path || null,
    trailer: pickTrailer(data.videos),
    cast: mapCast(data[creditsKey], type),
    seasons: type === 'tv' ? mapSeasons(data.seasons) : [],
    recommendations: ((data.recommendations && data.recommendations.results) || [])
      .filter((item) => !item.media_type || item.media_type === 'movie' || item.media_type === 'tv')
      .slice(0, RECOMMENDATIONS_LIMIT)
      .map((item) => toSummary(item, item.media_type || type)),
    providers,
    sagas: sagasForTitle(type, data.id, data.belongs_to_collection),
    availability: {
      release: releaseStatus(type, data),
      abroad: availableInBrazil ? [] : mapAbroad(providersByCountry)
    }
  };
}

async function handleApi(url) {
  if (url.pathname === '/api/list') return handleList(url.searchParams);
  if (url.pathname === '/api/search') return handleSearch(url.searchParams);
  if (url.pathname === '/api/sagas') return handleSagaList();
  if (url.pathname === '/api/sagas/search') return handleSagaSearch(url.searchParams);
  const collectionSaga = url.pathname.match(/^\/api\/saga\/collection\/(\d{1,10})$/);
  if (collectionSaga) return handleCollectionSaga(collectionSaga[1]);
  const curatedSaga = url.pathname.match(/^\/api\/saga\/curated\/([a-z0-9-]{1,40})$/);
  if (curatedSaga) return handleCuratedSaga(curatedSaga[1]);
  if (url.pathname === '/api/public-domain') return handlePublicDomainList(url.searchParams);
  const publicItem = url.pathname.match(/^\/api\/public-domain\/([A-Za-z0-9._-]{1,100})$/);
  if (publicItem) return handlePublicDomainItem(publicItem[1]);
  if (url.pathname === '/api/cinema') return handleCinema(url.searchParams);
  if (url.pathname === '/api/reminders/check') return handleReminderCheck(url.searchParams);
  if (url.pathname === '/api/platforms') return handlePlatforms();
  if (url.pathname === '/api/platform-top') return handlePlatformTop(url.searchParams);

  const genres = url.pathname.match(/^\/api\/genres\/(movie|tv)$/);
  if (genres) return handleGenres(genres[1]);

  const season = url.pathname.match(/^\/api\/title\/tv\/(\d{1,10})\/season\/(\d{1,3})$/);
  if (season) return handleSeason(season[1], season[2]);

  const title = url.pathname.match(/^\/api\/title\/(movie|tv)\/(\d{1,10})$/);
  if (title) return handleTitle(title[1], title[2]);

  throw new HttpError(404, 'Rota não encontrada.');
}

function sendJson(res, status, body) {
  res.writeHead(status, { ...SECURITY_HEADERS, 'Content-Type': 'application/json; charset=utf-8' });
  res.end(JSON.stringify(body));
}

function serveStatic(url, res) {
  const relative = url.pathname === '/' ? 'index.html' : decodeURIComponent(url.pathname).replace(/^\/+/, '');
  const filePath = path.resolve(PUBLIC_DIR, relative);

  if (!filePath.startsWith(PUBLIC_DIR + path.sep)) {
    res.writeHead(403, SECURITY_HEADERS);
    res.end();
    return;
  }

  fs.readFile(filePath, (error, content) => {
    if (error) {
      res.writeHead(404, { ...SECURITY_HEADERS, 'Content-Type': 'text/plain; charset=utf-8' });
      res.end('Não encontrado');
      return;
    }
    const type = MIME_TYPES[path.extname(filePath).toLowerCase()] || 'application/octet-stream';
    res.writeHead(200, { ...SECURITY_HEADERS, 'Content-Type': type });
    res.end(content);
  });
}

const server = http.createServer(async (req, res) => {
  if (req.method !== 'GET' && req.method !== 'HEAD') {
    res.writeHead(405, { ...SECURITY_HEADERS, Allow: 'GET, HEAD' });
    res.end();
    return;
  }

  let url;
  try {
    url = new URL(req.url, 'http://localhost');
  } catch {
    res.writeHead(400, SECURITY_HEADERS);
    res.end();
    return;
  }

  if (!url.pathname.startsWith('/api/')) {
    serveStatic(url, res);
    return;
  }

  try {
    sendJson(res, 200, await handleApi(url));
  } catch (error) {
    if (error instanceof HttpError) {
      sendJson(res, error.status, { error: error.message });
    } else {
      console.error(error);
      sendJson(res, 500, { error: 'Erro interno no servidor.' });
    }
  }
});

server.listen(PORT, () => {
  console.log(`Servidor rodando em http://localhost:${PORT}`);
  if (!TMDB_API_KEY) console.warn('Aviso: TMDB_API_KEY não definida. Crie o arquivo .env (veja .env.example).');
});
